runtime: python39  # or python310 for Python 3.10
entrypoint: gunicorn -b :$PORT run:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  FLASK_ENV: production
  SECRET_KEY: your_secret_key
